name: CI mobile

on:
  pull_request:
    branches:
      - main
    paths:
      - 'mobile/**'

env:
  IMAGE_TAG_MOBILE: mobile

jobs:
  build:
    name: Mobile - Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Build the Docker image
        working-directory: ./mobile
        run: docker build -t $IMAGE_TAG_MOBILE --target=create-build .
      - name: Run Prettier
        working-directory: ./mobile
        run: docker run $IMAGE_TAG_MOBILE sh -c 'npm run format:verify'
      - name: Run ESLint
        working-directory: ./mobile
        run: docker run $IMAGE_TAG_MOBILE sh -c 'npm run lint:verify'
      - name: Run tests
        working-directory: ./mobile
        run: docker run $IMAGE_TAG_MOBILE sh -c 'npm run test'
